In [1]:
import pandas as pd
from datetime import datetime

In [2]:
# csv_file0601 = '../../data/processed/advised_portfolios-0601.dat'
# df = pd.read_csv(csv_file0601, parse_dates=['date'])

In [3]:
# df.date = df.date.dt.strftime('%Y-%m-%d')

In [4]:
# df.to_pickle('../../data/processed/advised_portfolios-0601_new.pkl')

In [5]:
access_path = '../../data/processed/'
filename = ['advised_portfolios-start-to-20210601.pkl', 'advised_portfolios-0701.pkl']
full_path = [access_path + file_nm for file_nm in filename]

In [6]:
ports = [pd.read_pickle(file) for file in full_path]

In [7]:
ports[0]

,date,risk_profile,itemcode,weights,tracking_code,itemname,price,volume,trading_amt_mln,asset_class
0,2019-01-02,2,A273130,0.240000,ACT_BOND_D4,KODEX 종합채권(AA-이상)액티브,104320.0,26468.0,858.104496,Fixed Income
1,2019-01-02,2,A214980,0.240000,MM_PLUS,KODEX 단기채권PLUS,100050.0,10160.0,508.874866,Fixed Income
2,2019-01-02,2,A196230,0.207716,BOK_D.4,KBSTAR 단기통안채,101423.0,393085.0,16568.430895,Fixed Income
3,2019-01-02,2,A114260,0.100000,KTB_D3,KODEX 국고채3년,55690.0,5449.0,251.127486,Fixed Income
4,2019-01-02,2,A122260,0.092284,BOK_D1,KOSEF 통안채1년,97761.0,42453.0,13238.397304,Fixed Income
...,...,...,...,...,...,...,...,...,...,...
20057,2021-06-01,4,A157490,0.240000,SW,TIGER 소프트웨어,17690.0,148623.0,2490.713941,Equity
20058,2021-06-01,4,A278540,0.240000,MSCI_KR,KODEX MSCI Korea TR,13735.0,280278.0,9454.867980,Equity
20059,2021-06-01,4,A266370,0.136000,IT,KODEX IT,20325.0,10876.0,799.389367,Equity
20060,2021-06-01,4,A292150,0.084000,TOP10,TIGER TOP10,14360.0,328759.0,4720.979240,Equity
20061,2021-06-01,4,A114260,0.060000,KTB_D3,KODEX 국고채3년,57990.0,2678.0,790.152822,Fixed Income

In [8]:
ports[1]

,date,risk_profile,itemcode,weights,tracking_code,itemname,price,volume,trading_amt_mln,asset_class
0,2021-06-02,2,A114260,0.240000,KTB_D3,KODEX 국고채3년,57990.0,909.0,789.470750,Fixed Income
1,2021-06-02,2,A122260,0.240000,BOK_D1,KOSEF 통안채1년,101315.0,438652.0,41238.607663,Fixed Income
2,2021-06-02,2,A130730,0.240000,MM,KOSEF 단기자금,101155.0,2096724.0,74874.902886,Fixed Income
3,2021-06-02,2,A196230,0.086007,BOK_D.4,KBSTAR 단기통안채,104475.0,887131.0,51004.491715,Fixed Income
4,2021-06-02,2,A273130,0.073993,ACT_BOND_D4,KODEX 종합채권(AA-이상)액티브,108315.0,20277.0,2045.333438,Fixed Income
...,...,...,...,...,...,...,...,...,...,...
625,2021-07-01,4,A278540,0.240000,MSCI_KR,KODEX MSCI Korea TR,14010.0,321676.0,11167.465380,Equity
626,2021-07-01,4,A157490,0.240000,SW,TIGER 소프트웨어,19565.0,155273.0,2126.720790,Equity
627,2021-07-01,4,A266370,0.136000,IT,KODEX IT,21175.0,40721.0,486.859924,Equity
628,2021-07-01,4,A069500,0.084000,K200,KODEX 200,43640.0,3117261.0,251014.946316,Equity
629,2021-07-01,4,A114260,0.060000,KTB_D3,KODEX 국고채3년,57845.0,37695.0,590.640193,Fixed Income

In [9]:
df = pd.concat(ports, axis=0)
df = df.reset_index(drop=True)

In [10]:
df

,date,risk_profile,itemcode,weights,tracking_code,itemname,price,volume,trading_amt_mln,asset_class
0,2019-01-02,2,A273130,0.240000,ACT_BOND_D4,KODEX 종합채권(AA-이상)액티브,104320.0,26468.0,858.104496,Fixed Income
1,2019-01-02,2,A214980,0.240000,MM_PLUS,KODEX 단기채권PLUS,100050.0,10160.0,508.874866,Fixed Income
2,2019-01-02,2,A196230,0.207716,BOK_D.4,KBSTAR 단기통안채,101423.0,393085.0,16568.430895,Fixed Income
3,2019-01-02,2,A114260,0.100000,KTB_D3,KODEX 국고채3년,55690.0,5449.0,251.127486,Fixed Income
4,2019-01-02,2,A122260,0.092284,BOK_D1,KOSEF 통안채1년,97761.0,42453.0,13238.397304,Fixed Income
...,...,...,...,...,...,...,...,...,...,...
20687,2021-07-01,4,A278540,0.240000,MSCI_KR,KODEX MSCI Korea TR,14010.0,321676.0,11167.465380,Equity
20688,2021-07-01,4,A157490,0.240000,SW,TIGER 소프트웨어,19565.0,155273.0,2126.720790,Equity
20689,2021-07-01,4,A266370,0.136000,IT,KODEX IT,21175.0,40721.0,486.859924,Equity
20690,2021-07-01,4,A069500,0.084000,K200,KODEX 200,43640.0,3117261.0,251014.946316,Equity
20691,2021-07-01,4,A114260,0.060000,KTB_D3,KODEX 국고채3년,57845.0,37695.0,590.640193,Fixed Income

In [11]:
df.to_pickle(access_path + 'advised_portfolios.pkl')

In [9]:
import datetime
# BDay is business day, not birthday...
from pandas.tseries.offsets import BDay

today = datetime.datetime.today()
print(today - BDay(1))

2021-05-31 18:35:34.740596